services:
  mysql:
    image: mysql:8.0
    container_name: hmdp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123459
      MYSQL_DATABASE: hmdp
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - hmdp_mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    container_name: hmdp-redis
    ports:
      - "6379:6379"
    volumes:
      - hmdp_redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: hmdp-backend
#    depends_on:
#      - mysql
#      - redis
#    ports:
#      - "8081:8080"
#    environment:
#      TZ: Asia/Shanghai
#      SERVER_PORT: 8080
#
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hmdp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 123459
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
  nginx:
    image: nginx:alpine
    container_name: hmdp-nginx
#    depends_on:
#      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-1.18.0/html:/usr/share/nginx/html:ro
      - ./nginx-1.18.0/conf/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  hmdp_mysql_data:
  hmdp_redis_data: